name: prist

services:
  mongo:
    image: mongo:7.0.15
    container_name: mongo
    restart: always
    command: "/usr/bin/mongod --bind_ip_all --replSet rs" # startup container in replicaset with name 'rs' mode
    ports:
      - "27017:27017"
    healthcheck: # command to initiate replicaset with name 'rs' and register container as primary node in it
      test: |
        test $$(mongosh --quiet --eval "try { rs.initiate({ _id: 'rs', members: [{ _id: 0, host: 'localhost' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 5s