services:
  mongo:
    image: mongo:8.0.3
    restart: always
    container_name: prist_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    command: "/usr/bin/mongod --bind_ip_all --replSet rs" # startup container in replicaset with name 'rs' mode
    healthcheck: # command to initiate replicaset with name 'rs' and register container as primary node in it
      test: |
        test $$(mongosh --quiet --eval "try { rs.initiate({ _id: 'rs', members: [{ _id: 0, host: 'localhost' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 5s
    ports:
      - "27017:27017"
    volume:
      ./data/mongo:/data/db
